-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\addrAoffset.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: addrAoffset
-- Source Path: bandpass_eq/fftAnalysisSynthesis/analysis/fftFrameBuffering/addrAoffset
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY addrAoffset IS
  PORT( counterA                          :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
        addrA                             :   OUT   std_logic_vector(8 DOWNTO 0)  -- ufix9
        );
END addrAoffset;


ARCHITECTURE rtl OF addrAoffset IS

  -- Signals
  SIGNAL counterA_unsigned                : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL writeOffset_out1                 : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Add_out1                         : unsigned(8 DOWNTO 0);  -- ufix9

BEGIN
  -- Adding 1 to counter since the read pointer (addr_B) can catch the write pointer (addr_A) 
  -- if modelParams.system.upsampleFactor is large enough and Simulink will throw an error.  
  -- It would be nice if the HDL Coder allowed a read-before-write option when
  -- the addresses are identical, which some memories support.

  counterA_unsigned <= unsigned(counterA);

  writeOffset_out1 <= to_unsigned(16#001#, 9);

  Add_out1 <= counterA_unsigned + writeOffset_out1;

  addrA <= std_logic_vector(Add_out1);

END rtl;

