-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\fftFilterCoefficients.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fftFilterCoefficients
-- Source Path: bandpass_eq/fftAnalysisSynthesis/frequencyDomainProcessing/applyComplexGains/fftFilterCoefficients
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fftFilterCoefficients IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        gain_1                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
        gain_2                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
        gain_3                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
        gain_4                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
        gain_5                            :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
        fftValid                          :   IN    std_logic;
        filterCoefficients_re             :   OUT   std_logic_vector(34 DOWNTO 0);  -- sfix35_En22
        filterCoefficients_im             :   OUT   std_logic_vector(34 DOWNTO 0)  -- sfix35_En22
        );
END fftFilterCoefficients;


ARCHITECTURE rtl OF fftFilterCoefficients IS

  -- Component Declarations
  COMPONENT fftROMindexing
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          fftValid                        :   IN    std_logic;
          ROMindex                        :   OUT   std_logic_vector(9 DOWNTO 0);  -- sfix10
          conjugate                       :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT filterChoice
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          gain_1                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
          gain_2                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
          gain_3                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
          gain_4                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
          gain_5                          :   IN    std_logic_vector(15 DOWNTO 0);  -- ufix16_En14
          ROMindex                        :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
          conjugate                       :   IN    std_logic;
          filterCoefficients_re           :   OUT   std_logic_vector(34 DOWNTO 0);  -- sfix35_En22
          filterCoefficients_im           :   OUT   std_logic_vector(34 DOWNTO 0)  -- sfix35_En22
          );
  END COMPONENT;

  -- Signals
  SIGNAL fftROMindexing_out1              : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL fftROMindexing_out2              : std_logic;
  SIGNAL filterChoice_out1_re             : std_logic_vector(34 DOWNTO 0);  -- ufix35
  SIGNAL filterChoice_out1_im             : std_logic_vector(34 DOWNTO 0);  -- ufix35

BEGIN
  u_fftROMindexing : fftROMindexing
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              fftValid => fftValid,
              ROMindex => fftROMindexing_out1,  -- sfix10
              conjugate => fftROMindexing_out2
              );

  u_filterChoice : filterChoice
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              gain_1 => gain_1,  -- ufix16_En14
              gain_2 => gain_2,  -- ufix16_En14
              gain_3 => gain_3,  -- ufix16_En14
              gain_4 => gain_4,  -- ufix16_En14
              gain_5 => gain_5,  -- ufix16_En14
              ROMindex => fftROMindexing_out1,  -- sfix10
              conjugate => fftROMindexing_out2,
              filterCoefficients_re => filterChoice_out1_re,  -- sfix35_En22
              filterCoefficients_im => filterChoice_out1_im  -- sfix35_En22
              );

  filterCoefficients_re <= filterChoice_out1_re;

  filterCoefficients_im <= filterChoice_out1_im;

END rtl;

