-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\fftROMindexing.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fftROMindexing
-- Source Path: bandpass_eq/fftAnalysisSynthesis/frequencyDomainProcessing/applyComplexGains/fftFilterCoefficients/fftROMindexing
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fftROMindexing IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        fftValid                          :   IN    std_logic;
        ROMindex                          :   OUT   std_logic_vector(9 DOWNTO 0);  -- sfix10
        conjugate                         :   OUT   std_logic
        );
END fftROMindexing;


ARCHITECTURE rtl OF fftROMindexing IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT Decrement_Stored_Integer
    PORT( u                               :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
          y                               :   OUT   std_logic_vector(9 DOWNTO 0)  -- sfix10
          );
  END COMPONENT;

  -- Signals
  SIGNAL Bitwise_Operator_out1            : std_logic;
  SIGNAL count_step                       : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_reset                      : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL fftIndexCount_out1               : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count                            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_1                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL count_2                          : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Constant5_out1                   : unsigned(7 DOWNTO 0);  -- uint8
  SIGNAL Relational_Operator_relop1       : std_logic;
  SIGNAL switch_compare_1                 : std_logic;
  SIGNAL Constant1_out1                   : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Add_sub_cast                     : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Add_sub_cast_1                   : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Add_out1                         : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL fftIndexCount_out1_dtc           : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Switch_out1                      : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL Decrement_Stored_Integer_out1    : std_logic_vector(9 DOWNTO 0);  -- ufix10
  SIGNAL Bitwise_Operator1_out1           : std_logic;

BEGIN
  -- ROM is indexed by k=i-1 (zero offset)
  -- so decrement by one.
  -- Determine when we transition to the
  -- negative frequencies in the FFT frame
  -- Matlab FFT index i = 1:NFFT
  -- Matlab conjugate index = NFFT - i + 2
  -- Assert conjugation when counting through 
  -- the conjugate negative frequencies.
  -- If we are dealing with negative frequencies 
  -- we need to know when to apply a 
  -- conjugation operation.
  -- Count from 1 to NFFT 
  -- while fftValid is asserted

  u_Decrement_Stored_Integer : Decrement_Stored_Integer
    PORT MAP( u => std_logic_vector(Switch_out1),  -- sfix10
              y => Decrement_Stored_Integer_out1  -- sfix10
              );

  Bitwise_Operator_out1 <=  NOT fftValid;

  -- Free running, Unsigned Counter
  --  initial value   = 0
  --  step value      = 1
  count_step <= to_unsigned(16#001#, 9);

  count_reset <= to_unsigned(16#000#, 9);

  count <= fftIndexCount_out1 + count_step;

  
  count_1 <= fftIndexCount_out1 WHEN fftValid = '0' ELSE
      count;

  
  count_2 <= count_1 WHEN Bitwise_Operator_out1 = '0' ELSE
      count_reset;

  fftIndexCount_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      fftIndexCount_out1 <= to_unsigned(16#000#, 9);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        fftIndexCount_out1 <= count_2;
      END IF;
    END IF;
  END PROCESS fftIndexCount_process;


  Constant5_out1 <= to_unsigned(16#81#, 8);

  
  Relational_Operator_relop1 <= '1' WHEN fftIndexCount_out1 <= resize(Constant5_out1, 9) ELSE
      '0';

  
  switch_compare_1 <= '1' WHEN Relational_Operator_relop1 > '0' ELSE
      '0';

  Constant1_out1 <= to_unsigned(16#102#, 9);

  Add_sub_cast <= signed(resize(Constant1_out1, 10));
  Add_sub_cast_1 <= signed(resize(fftIndexCount_out1, 10));
  Add_out1 <= Add_sub_cast - Add_sub_cast_1;

  fftIndexCount_out1_dtc <= signed(resize(fftIndexCount_out1, 10));

  
  Switch_out1 <= Add_out1 WHEN switch_compare_1 = '0' ELSE
      fftIndexCount_out1_dtc;

  Bitwise_Operator1_out1 <=  NOT Relational_Operator_relop1;

  ROMindex <= Decrement_Stored_Integer_out1;

  conjugate <= Bitwise_Operator1_out1;

END rtl;

