-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\filter1Coefficients.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: filter1Coefficients
-- Source Path: bandpass_eq/fftAnalysisSynthesis/frequencyDomainProcessing/applyComplexGains/fftFilterCoefficients/filterChoice/filter1Coefficients
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.fftAnalysisSynthesis_pkg.ALL;

ENTITY filter1Coefficients IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        ROMindex                          :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
        conjugate                         :   IN    std_logic;
        complexCoefficients_re            :   OUT   std_logic_vector(15 DOWNTO 0);  -- sfix16_En8
        complexCoefficients_im            :   OUT   std_logic_vector(15 DOWNTO 0)  -- sfix16_En8
        );
END filter1Coefficients;


ARCHITECTURE rtl OF filter1Coefficients IS

  -- Constants
  CONSTANT filter1RealCoefficients_table_data : vector_of_signed16(0 TO 127) := 
    (to_signed(16#0100#, 16), to_signed(16#0100#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16),
     to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16), to_signed(16#0000#, 16));  -- sfix16 [128]

  -- Signals
  SIGNAL ROMindex_signed                  : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL filter1RealCoefficients_index    : signed(31 DOWNTO 0);  -- int32
  SIGNAL filter1RealCoefficients_out1     : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL filter1RealCoefficients_out1_1   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En8
  SIGNAL conjugate_1                      : std_logic;
  SIGNAL filter1ImagCoefficients_out1     : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL filter1ImagCoefficients_out1_1   : signed(15 DOWNTO 0) := to_signed(16#0000#, 16);  -- sfix16_En8
  SIGNAL Unary_Minus_cast                 : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Unary_Minus_cast_1               : signed(16 DOWNTO 0);  -- sfix17_En8
  SIGNAL Unary_Minus_out1                 : signed(15 DOWNTO 0);  -- sfix16_En8
  SIGNAL Switch_out1                      : signed(15 DOWNTO 0);  -- sfix16_En8

BEGIN
  -- The coefficients are only stored for the positive frequencies
  -- The same coefficients are used for the negative frequencies but with a sign change.
  -- When conjugate is asserted
  -- change the sign of the complex term.
  -- Perform conjuation of the imaginary term
  -- for the negative frequencies

  ROMindex_signed <= signed(ROMindex);

  
  filter1RealCoefficients_index <= to_signed(16#0000007F#, 32) WHEN ROMindex_signed > to_signed(16#0000007F#, 10) ELSE
      resize(ROMindex_signed, 32);
  filter1RealCoefficients_out1 <= filter1RealCoefficients_table_data(to_integer(filter1RealCoefficients_index));

  PipelineRegister1_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF enb = '1' THEN
        filter1RealCoefficients_out1_1 <= filter1RealCoefficients_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister1_process;


  complexCoefficients_re <= std_logic_vector(filter1RealCoefficients_out1_1);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      conjugate_1 <= '0';
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        conjugate_1 <= conjugate;
      END IF;
    END IF;
  END PROCESS delayMatch_process;


  filter1ImagCoefficients_out1 <= to_signed(16#0000#, 16);

  PipelineRegister_process : PROCESS (clk)
  BEGIN
    IF rising_edge(clk) THEN
      IF enb = '1' THEN
        filter1ImagCoefficients_out1_1 <= filter1ImagCoefficients_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  Unary_Minus_cast <= resize(filter1ImagCoefficients_out1_1, 17);
  Unary_Minus_cast_1 <=  - (Unary_Minus_cast);
  Unary_Minus_out1 <= Unary_Minus_cast_1(15 DOWNTO 0);

  
  Switch_out1 <= filter1ImagCoefficients_out1_1 WHEN conjugate_1 = '0' ELSE
      Unary_Minus_out1;

  complexCoefficients_im <= std_logic_vector(Switch_out1);

END rtl;

