-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\Decrement_Stored_Integer.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Decrement_Stored_Integer
-- Source Path: bandpass_eq/fftAnalysisSynthesis/frequencyDomainProcessing/applyComplexGains/fftFilterCoefficients/fftROMindexing/Decrement 
-- Stored Intege
-- Hierarchy Level: 5
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY Decrement_Stored_Integer IS
  PORT( u                                 :   IN    std_logic_vector(9 DOWNTO 0);  -- sfix10
        y                                 :   OUT   std_logic_vector(9 DOWNTO 0)  -- sfix10
        );
END Decrement_Stored_Integer;


ARCHITECTURE rtl OF Decrement_Stored_Integer IS

  -- Signals
  SIGNAL u_signed                         : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL FixPt_Constant_out1              : signed(9 DOWNTO 0);  -- sfix10
  SIGNAL FixPt_Sum1_out1                  : signed(9 DOWNTO 0);  -- sfix10

BEGIN
  u_signed <= signed(u);

  FixPt_Constant_out1 <= to_signed(16#001#, 10);

  FixPt_Sum1_out1 <= u_signed - FixPt_Constant_out1;

  y <= std_logic_vector(FixPt_Sum1_out1);


END rtl;

