-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\fifoWriteSelect.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fifoWriteSelect
-- Source Path: bandpass_eq/fftAnalysisSynthesis/synthesis/overlapAdd/fifoWriteSelect
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.fftAnalysisSynthesis_pkg.ALL;

ENTITY fifoWriteSelect IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        fifoCounter                       :   IN    std_logic_vector(1 DOWNTO 0);  -- ufix2
        validSignal                       :   IN    std_logic;
        valid1                            :   OUT   std_logic;
        valid2                            :   OUT   std_logic;
        valid3                            :   OUT   std_logic;
        valid4                            :   OUT   std_logic
        );
END fifoWriteSelect;


ARCHITECTURE rtl OF fifoWriteSelect IS

  ATTRIBUTE multstyle : string;

  -- Signals
  SIGNAL fifoCounter_unsigned             : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL delayMatch_reg                   : vector_of_unsigned2(0 TO 9);  -- ufix2 [10]
  SIGNAL fifoCounter_1                    : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  fifoCounter_unsigned <= unsigned(fifoCounter);

  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => to_unsigned(16#0#, 2));
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= fifoCounter_unsigned;
        delayMatch_reg(1 TO 9) <= delayMatch_reg(0 TO 8);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  fifoCounter_1 <= delayMatch_reg(9);

  fifoWriteSelect_1_output : PROCESS (fifoCounter_1, validSignal)
  BEGIN
    --MATLAB Function 'fftAnalysisSynthesis/synthesis/overlapAdd/fifoWriteSelect'
    CASE fifoCounter_1 IS
      WHEN "00" =>
        valid1 <= validSignal;
        valid2 <= '0';
        valid3 <= '0';
        valid4 <= '0';
      WHEN "01" =>
        valid1 <= '0';
        valid2 <= validSignal;
        valid3 <= '0';
        valid4 <= '0';
      WHEN "10" =>
        valid1 <= '0';
        valid2 <= '0';
        valid3 <= validSignal;
        valid4 <= '0';
      WHEN "11" =>
        valid1 <= '0';
        valid2 <= '0';
        valid3 <= '0';
        valid4 <= validSignal;
      WHEN OTHERS => 
        valid1 <= '0';
        valid2 <= '0';
        valid3 <= '0';
        valid4 <= '0';
    END CASE;
  END PROCESS fifoWriteSelect_1_output;


END rtl;

