-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\fftFramePulseGen.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fftFramePulseGen
-- Source Path: bandpass_eq/fftAnalysisSynthesis/analysis/fftFrameBuffering/fftPulseGen/fftFramePulseGen
-- Hierarchy Level: 4
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fftFramePulseGen IS
  PORT( counterValue                      :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
        framePulse                        :   OUT   std_logic
        );
END fftFramePulseGen;


ARCHITECTURE rtl OF fftFramePulseGen IS

  -- Signals
  SIGNAL counterValue_unsigned            : unsigned(8 DOWNTO 0);  -- ufix9
  SIGNAL Bit_Slice_out1                   : unsigned(5 DOWNTO 0);  -- ufix6
  SIGNAL Compare_To_Zero_out1             : std_logic;

BEGIN
  -- Create a FFT frame pulse that happens every FFT_size/4 samples.
  -- We do this by watching when an appropriate subset of the counter bits 
  -- become zero.

  counterValue_unsigned <= unsigned(counterValue);

  Bit_Slice_out1 <= counterValue_unsigned(5 DOWNTO 0);

  
  Compare_To_Zero_out1 <= '1' WHEN Bit_Slice_out1 = to_unsigned(16#00#, 6) ELSE
      '0';

  framePulse <= Compare_To_Zero_out1;

END rtl;

