-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\fftPulseGen.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fftPulseGen
-- Source Path: bandpass_eq/fftAnalysisSynthesis/analysis/fftFrameBuffering/fftPulseGen
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fftPulseGen IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        counter                           :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
        fftStartPulse                     :   OUT   std_logic
        );
END fftPulseGen;


ARCHITECTURE rtl OF fftPulseGen IS

  -- Component Declarations
  COMPONENT fftFramePulseGen
    PORT( counterValue                    :   IN    std_logic_vector(8 DOWNTO 0);  -- ufix9
          framePulse                      :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT waitForData
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          framePulse                      :   IN    std_logic;
          fftFramePulse                   :   OUT   std_logic
          );
  END COMPONENT;

  -- Signals
  SIGNAL fftFramePulseGen_out1            : std_logic;
  SIGNAL waitForData_out1                 : std_logic;

BEGIN
  -- Don't send out FFT frame start pulses 
  -- until circular buffer has filled.

  u_fftFramePulseGen : fftFramePulseGen
    PORT MAP( counterValue => counter,  -- ufix9
              framePulse => fftFramePulseGen_out1
              );

  u_waitForData : waitForData
    PORT MAP( clk => clk,
              reset => reset,
              enb_1_2048_0 => enb_1_2048_0,
              framePulse => fftFramePulseGen_out1,
              fftFramePulse => waitForData_out1
              );

  fftStartPulse <= waitForData_out1;

END rtl;

