-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\fifoStateMachine1.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: fifoStateMachine1
-- Source Path: bandpass_eq/fftAnalysisSynthesis/synthesis/overlapAdd/fifoStateMachine1
-- Hierarchy Level: 3
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY fifoStateMachine1 IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        valid                             :   IN    std_logic;
        pop                               :   OUT   std_logic
        );
END fifoStateMachine1;


ARCHITECTURE rtl OF fifoStateMachine1 IS

  ATTRIBUTE multstyle : string;

  -- Signals
  SIGNAL current_state                    : unsigned(1 DOWNTO 0);  -- ufix2
  SIGNAL current_state_next               : unsigned(1 DOWNTO 0);  -- ufix2

BEGIN
  fifoStateMachine1_1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      current_state <= to_unsigned(16#0#, 2);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        current_state <= current_state_next;
      END IF;
    END IF;
  END PROCESS fifoStateMachine1_1_process;

  fifoStateMachine1_1_output : PROCESS (current_state, valid)
  BEGIN
    current_state_next <= current_state;
    --MATLAB Function 'fftAnalysisSynthesis/synthesis/overlapAdd/fifoStateMachine1'
    CASE current_state IS
      WHEN "00" =>
        -- what for iFFTValid signal to be asserted for the first time
        pop <= '0';
        IF valid = '1' THEN 
          current_state_next <= to_unsigned(16#1#, 2);
        ELSE 
          current_state_next <= to_unsigned(16#0#, 2);
        END IF;
      WHEN "01" =>
        -- wait until the iFFTValid signal is deasserted
        pop <= '0';
        IF valid = '1' THEN 
          current_state_next <= to_unsigned(16#1#, 2);
        ELSE 
          current_state_next <= to_unsigned(16#2#, 2);
        END IF;
      WHEN "10" =>
        -- assert pop signal forever after first iFFTValid signal
        pop <= '1';
        current_state_next <= to_unsigned(16#2#, 2);
      WHEN OTHERS => 
        pop <= '0';
    END CASE;
  END PROCESS fifoStateMachine1_1_output;


END rtl;

