-- -------------------------------------------------------------
-- 
-- File Name: C:\Users\Antho\Desktop\EELE_468\eq\hdlsrc\bandpass_eq\synthesis.vhd
-- 
-- Generated by MATLAB 9.14 and HDL Coder 4.1
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: synthesis
-- Source Path: bandpass_eq/fftAnalysisSynthesis/synthesis
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;

ENTITY synthesis IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        enb_1_2048_0                      :   IN    std_logic;
        enb_1_2048_1                      :   IN    std_logic;
        enb_1_1_1                         :   IN    std_logic;
        enb_1_2048_11                     :   IN    std_logic;
        fftModifiedData_re                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
        fftModifiedData_im                :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
        fftValid                          :   IN    std_logic;
        fftFramePulse                     :   IN    std_logic;
        audioOut                          :   OUT   std_logic_vector(23 DOWNTO 0)  -- sfix24_En23
        );
END synthesis;


ARCHITECTURE rtl OF synthesis IS

  ATTRIBUTE multstyle : string;

  -- Component Declarations
  COMPONENT iFFT
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          dataIn_re                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          dataIn_im                       :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          validIn                         :   IN    std_logic;
          dataOut_re                      :   OUT   std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          validOut                        :   OUT   std_logic
          );
  END COMPONENT;

  COMPONENT overlapAdd
    PORT( clk                             :   IN    std_logic;
          reset                           :   IN    std_logic;
          enb                             :   IN    std_logic;
          enb_1_2048_0                    :   IN    std_logic;
          enb_1_2048_1                    :   IN    std_logic;
          enb_1_1_1                       :   IN    std_logic;
          enb_1_2048_11                   :   IN    std_logic;
          iFFTData                        :   IN    std_logic_vector(31 DOWNTO 0);  -- sfix32_En23
          iFFTValid                       :   IN    std_logic;
          fftFramePulse                   :   IN    std_logic;
          audioOut                        :   OUT   std_logic_vector(33 DOWNTO 0)  -- sfix34_En23
          );
  END COMPONENT;

  -- Signals
  SIGNAL kconst                           : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL kconst_1                         : signed(33 DOWNTO 0);  -- sfix34_En33
  SIGNAL delayMatch_reg                   : std_logic_vector(0 TO 6);  -- ufix1 [7]
  SIGNAL fftValid_1                       : std_logic;
  SIGNAL iFFT_out1_re                     : std_logic_vector(31 DOWNTO 0);  -- ufix32
  SIGNAL iFFT_out2                        : std_logic;
  SIGNAL overlapAdd_out1                  : std_logic_vector(33 DOWNTO 0);  -- ufix34
  SIGNAL overlapAdd_out1_1                : signed(33 DOWNTO 0);  -- sfix34_En23
  SIGNAL overlapAdd_out1_2                : signed(33 DOWNTO 0);  -- sfix34_En23
  SIGNAL Gain_out1                        : signed(67 DOWNTO 0);  -- sfix68_En56
  SIGNAL Gain_out1_1                      : signed(67 DOWNTO 0);  -- sfix68_En56
  SIGNAL Gain_out1_2                      : signed(23 DOWNTO 0);  -- sfix24_En23
  SIGNAL t_bypass_reg                     : signed(23 DOWNTO 0);  -- sfix24
  SIGNAL Gain_out1_3                      : signed(23 DOWNTO 0);  -- sfix24_En23

BEGIN
  -- Making the assumption that the frequency domain processing preserved the complex conjugate pairs so that the output 
  -- is real and we can discard the zero imaginary term

  u_iFFT : iFFT
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              dataIn_re => fftModifiedData_re,  -- sfix32_En23
              dataIn_im => fftModifiedData_im,  -- sfix32_En23
              validIn => fftValid_1,
              dataOut_re => iFFT_out1_re,  -- sfix32_En23
              validOut => iFFT_out2
              );

  u_overlapAdd : overlapAdd
    PORT MAP( clk => clk,
              reset => reset,
              enb => enb,
              enb_1_2048_0 => enb_1_2048_0,
              enb_1_2048_1 => enb_1_2048_1,
              enb_1_1_1 => enb_1_1_1,
              enb_1_2048_11 => enb_1_2048_11,
              iFFTData => iFFT_out1_re,  -- sfix32_En23
              iFFTValid => iFFT_out2,
              fftFramePulse => fftFramePulse,
              audioOut => overlapAdd_out1  -- sfix34_En23
              );

  kconst <= signed'("0101001100110011001100110011001101");

  HwModeRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      kconst_1 <= to_signed(0, 34);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        kconst_1 <= kconst;
      END IF;
    END IF;
  END PROCESS HwModeRegister_process;


  delayMatch_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delayMatch_reg <= (OTHERS => '0');
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        delayMatch_reg(0) <= fftValid;
        delayMatch_reg(1 TO 6) <= delayMatch_reg(0 TO 5);
      END IF;
    END IF;
  END PROCESS delayMatch_process;

  fftValid_1 <= delayMatch_reg(6);

  overlapAdd_out1_1 <= signed(overlapAdd_out1);

  HwModeRegister1_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      overlapAdd_out1_2 <= to_signed(0, 34);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        overlapAdd_out1_2 <= overlapAdd_out1_1;
      END IF;
    END IF;
  END PROCESS HwModeRegister1_process;


  Gain_out1 <= kconst_1 * overlapAdd_out1_2;

  PipelineRegister_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      Gain_out1_1 <= to_signed(0, 68);
    ELSIF rising_edge(clk) THEN
      IF enb = '1' THEN
        Gain_out1_1 <= Gain_out1;
      END IF;
    END IF;
  END PROCESS PipelineRegister_process;


  Gain_out1_2 <= Gain_out1_1(56 DOWNTO 33);

  t_bypass_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      t_bypass_reg <= to_signed(16#000000#, 24);
    ELSIF rising_edge(clk) THEN
      IF enb_1_2048_1 = '1' THEN
        t_bypass_reg <= Gain_out1_2;
      END IF;
    END IF;
  END PROCESS t_bypass_process;

  
  Gain_out1_3 <= Gain_out1_2 WHEN enb_1_2048_1 = '1' ELSE
      t_bypass_reg;

  audioOut <= std_logic_vector(Gain_out1_3);

END rtl;

